spring.application.name=prestamil

# Database Configuration
spring.datasource.url=jdbc:mariadb://10.103.133.1:3306/CasaEmp_DEV
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=$IgnisD3v_2025

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Spring Session JDBC Configuration
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=embedded
spring.session.timeout.in-seconds=1800

# Server Servlet Cookie Configuration
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=Strict
# server.servlet.session.cookie.secure=true # Uncomment in production with HTTPS
