spring.application.name=prestamil

# Database Configuration
spring.datasource.url=jdbc:mariadb://10.103.133.1:3306/CasaEmp_DEV
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=$IgnisD3v_2025

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Configuration
jwt.secret=PrestamilSecretKey2024_MuySegura_ParaProduccion
jwt.expiration=86400000
